packages:
  - 'rs-x-core'
  - 'rs-x-state-manager'
  - 'rs-x-expression-parser'
  - 'rs-x-compiler'
  - 'rs-x-typescript-plugin'
  - 'rs-x-vscode-extension'
  - 'rs-x-cli'
  - 'rs-x-react'
  - 'rs-x-vue'
  - 'rs-x-react-components'
  - 'rs-x-dev-tools'
  - 'rs-x-angular/projects/*'
  - 'rs-x-expression-editor'
  - 'rs-x-site'
  - 'rs-x-ui'
  - 'rs-x-compiler-demo'
