/**
 * Benchmark data for the Angular Signals vs rs-x comparison.
 *
 * Generated by:
 *   node --expose-gc rs-x-expression-parser/scripts/benchmark-angular-signals-comparison.mjs
 *
 * Machine: Apple M4, 16 GB RAM, darwin/arm64, Node.js v25.4.0
 * Date: 2026-03-28
 */

export type SignalsComparisonRow = {
  bindings: number;
  rsx: {
    bindMs: number;
    singleUpdateMs: number;
    bulkUpdateMs: number;
  };
  angular: {
    bindMs: number;
    singleUpdateMs: number;
    bulkUpdateMs: number;
  };
};

export type SameModelRow = {
  /** Number of expression bindings (fixed at 1000 — one per generated expression). */
  bindings: number;
  /** Number of sequential x-changes in the bulk-update measurement. */
  bulkRounds: number;
  rsx: {
    /** Create+init only (no dispose). */
    bindMs: number;
    /**
     * Dispose cost measured separately because disposing N expressions from the
     * same model is O(N²): each dispose removes a subscriber from a watcher list
     * that still has N-i entries. This is teardown cost, not setup cost.
     */
    disposeMs: number;
    /** Change x once → all 1000 expressions re-evaluate. */
    singleUpdateMs: number;
    /** bulkRounds sequential x-changes, all 1000 re-evaluate each round. */
    bulkUpdateMs: number;
  };
  angular: {
    bindMs: number;
    singleUpdateMs: number;
    bulkUpdateMs: number;
  };
};

// ─── Scenario 1: Sync identifier ─────────────────────────────────────────────
// Each of the N bindings watches a unique field (`fieldN`) on its own model.
//   rs-x:     rsx('fieldN')(model)         — Proxy-based watching, async microtask
//   Angular:  signal(v) + computed(() => s()) — explicit reactive primitive, sync

export const syncIdentifierRows: SignalsComparisonRow[] = [
  {
    bindings: 1000,
    rsx:     { bindMs: 27.93,  singleUpdateMs: 0.1026, bulkUpdateMs: 5.52  },
    angular: { bindMs: 0.72,   singleUpdateMs: 0.0106, bulkUpdateMs: 0.22  },
  },
  {
    bindings: 3000,
    rsx:     { bindMs: 97.11,  singleUpdateMs: 0.0715, bulkUpdateMs: 14.99 },
    angular: { bindMs: 1.74,   singleUpdateMs: 0.0077, bulkUpdateMs: 0.93  },
  },
  {
    bindings: 5000,
    rsx:     { bindMs: 163.39, singleUpdateMs: 0.0687, bulkUpdateMs: 25.48 },
    angular: { bindMs: 3.02,   singleUpdateMs: 0.0092, bulkUpdateMs: 1.62  },
  },
  {
    bindings: 10000,
    rsx:     { bindMs: 337.12, singleUpdateMs: 0.0724, bulkUpdateMs: 50.10 },
    angular: { bindMs: 4.84,   singleUpdateMs: 0.0100, bulkUpdateMs: 3.83  },
  },
];

// ─── Scenario 2: Async identifier (BehaviorSubject) ──────────────────────────
// Each model field is a BehaviorSubject. The binding tracks the emitted value.
//   rs-x:     rsx('stream')(model)              — auto-subscribes to observable
//   Angular:  toSignal(behaviorSubject, {injector}) — synchronous on emit

export const asyncIdentifierRows: SignalsComparisonRow[] = [
  {
    bindings: 1000,
    rsx:     { bindMs: 31.75,  singleUpdateMs: 0.0505, bulkUpdateMs: 6.99  },
    angular: { bindMs: 1.81,   singleUpdateMs: 0.0167, bulkUpdateMs: 1.42  },
  },
  {
    bindings: 3000,
    rsx:     { bindMs: 123.48, singleUpdateMs: 0.0571, bulkUpdateMs: 19.07 },
    angular: { bindMs: 3.29,   singleUpdateMs: 0.0119, bulkUpdateMs: 3.09  },
  },
  {
    bindings: 5000,
    rsx:     { bindMs: 206.83, singleUpdateMs: 0.0602, bulkUpdateMs: 31.49 },
    angular: { bindMs: 5.13,   singleUpdateMs: 0.0111, bulkUpdateMs: 5.62  },
  },
  {
    bindings: 10000,
    rsx:     { bindMs: 435.31, singleUpdateMs: 0.0597, bulkUpdateMs: 59.46 },
    angular: { bindMs: 13.66,  singleUpdateMs: 0.0120, bulkUpdateMs: 6.44  },
  },
];

// ─── Scenario 3: Same-model — all 1000 generated complex expressions ──────────
// All 1000 generated expressions (from generated-benchmark-expression-strings.ts)
// are bound to ONE shared model { x, y }. These are deeply-nested arithmetic
// expressions, each with 60–100+ AST nodes.
//   rs-x:     rsx(generatedExpression[i])({ x, y }) — AST-based evaluation
//   Angular:  computed(() => new Function('x','y', expr)(xSig(), ySig()))
//             — compiled to native JS, full JIT speed
//
// "Single update" = change x once → all 1000 dependents re-evaluate.
// "Bulk update"   = 10 sequential x-changes, 1000 re-evaluations each round.

export const sameModelExpressionsRow: SameModelRow = {
  bindings: 1000,
  bulkRounds: 10,
  rsx:     { bindMs: 397, disposeMs: 36, singleUpdateMs: 118, bulkUpdateMs: 1067 },
  angular: { bindMs: 0.63, singleUpdateMs: 1.099, bulkUpdateMs: 12.08 },
};
