/**
 * Benchmark data for the Angular Signals vs rs-x comparison.
 *
 * Generated by:
 *   node --expose-gc rs-x-expression-parser/scripts/benchmark-angular-signals-comparison.mjs
 *
 * Machine: Apple M4, 16 GB RAM, darwin/arm64, Node.js v25.4.0
 * Date: 2026-03-29
 */

export const angularSignalsComparisonBenchmark = {
  date: '2026-03-29',
  compiledReport:
    'reports/angular-signals-comparison/benchmark-2026-03-29-compiled.json',
  treeReport: 'reports/angular-signals-comparison/benchmark-2026-03-29-tree.json',
};

type RuntimeMetrics = {
  bindMs: number;
  singleUpdateMs: number;
  bulkUpdateMs: number;
};

export type SignalsComparisonRow = {
  bindings: number;
  rsxCompiled: RuntimeMetrics;
  rsxTree: RuntimeMetrics;
  angular: RuntimeMetrics;
};

export type SameModelRow = {
  bindings: number;
  bulkRounds: number;
  rsxCompiled: {
    bindMs: number;
    disposeMs: number;
    singleUpdateMs: number;
    bulkUpdateMs: number;
  };
  rsxTree: {
    bindMs: number;
    disposeMs: number;
    singleUpdateMs: number;
    bulkUpdateMs: number;
  };
  angular: {
    bindMs: number;
    singleUpdateMs: number;
    bulkUpdateMs: number;
  };
};

export const syncIdentifierRows: SignalsComparisonRow[] = [
  {
    bindings: 1000,
    rsxCompiled: {
      bindMs: 34.30241700000005,
      singleUpdateMs: 0.11079150000000482,
      bulkUpdateMs: 6.340415999999948,
    },
    rsxTree: {
      bindMs: 33.856416000000024,
      singleUpdateMs: 0.11370850000002974,
      bulkUpdateMs: 6.697375000000022,
    },
    angular: {
      bindMs: 0.923041000000012,
      singleUpdateMs: 0.013583000000039647,
      bulkUpdateMs: 0.38164549999999053,
    },
  },
  {
    bindings: 3000,
    rsxCompiled: {
      bindMs: 146.94012500000008,
      singleUpdateMs: 0.08739549999995688,
      bulkUpdateMs: 17.674187500000016,
    },
    rsxTree: {
      bindMs: 118.55699999999979,
      singleUpdateMs: 0.08045849999984966,
      bulkUpdateMs: 17.601499999999987,
    },
    angular: {
      bindMs: 2.4234590000005483,
      singleUpdateMs: 0.010041999999884865,
      bulkUpdateMs: 1.2958959999996296,
    },
  },
  {
    bindings: 5000,
    rsxCompiled: {
      bindMs: 229.56187500000033,
      singleUpdateMs: 0.08104199999979755,
      bulkUpdateMs: 29.741667000000234,
    },
    rsxTree: {
      bindMs: 226.45187549999991,
      singleUpdateMs: 0.08966599999985192,
      bulkUpdateMs: 29.552708000000166,
    },
    angular: {
      bindMs: 3.910874500000318,
      singleUpdateMs: 0.011457999999038293,
      bulkUpdateMs: 2.0398330000007263,
    },
  },
  {
    bindings: 10000,
    rsxCompiled: {
      bindMs: 475.55075000000033,
      singleUpdateMs: 0.10656299999936891,
      bulkUpdateMs: 56.222312499999134,
    },
    rsxTree: {
      bindMs: 466.62316699999974,
      singleUpdateMs: 0.07854149999911897,
      bulkUpdateMs: 53.14960449999944,
    },
    angular: {
      bindMs: 6.622457999999824,
      singleUpdateMs: 0.01420849999976781,
      bulkUpdateMs: 4.977708500000517,
    },
  },
];

export const asyncIdentifierRows: SignalsComparisonRow[] = [
  {
    bindings: 1000,
    rsxCompiled: {
      bindMs: 41.82183299999815,
      singleUpdateMs: 0.06527050000113377,
      bulkUpdateMs: 8.926416500000414,
    },
    rsxTree: {
      bindMs: 41.742041999999856,
      singleUpdateMs: 0.06041699999877892,
      bulkUpdateMs: 8.582479500000773,
    },
    angular: {
      bindMs: 3.513542000000598,
      singleUpdateMs: 0.0203334999987419,
      bulkUpdateMs: 1.4287920000006125,
    },
  },
  {
    bindings: 3000,
    rsxCompiled: {
      bindMs: 178.78758300000118,
      singleUpdateMs: 0.07150000000001455,
      bulkUpdateMs: 22.780312499999127,
    },
    rsxTree: {
      bindMs: 179.26833299999998,
      singleUpdateMs: 0.08272900000156369,
      bulkUpdateMs: 23.16039600000113,
    },
    angular: {
      bindMs: 5.745624999999563,
      singleUpdateMs: 0.01524999999855936,
      bulkUpdateMs: 4.163541500000065,
    },
  },
  {
    bindings: 5000,
    rsxCompiled: {
      bindMs: 291.30943750000006,
      singleUpdateMs: 0.06650000000081491,
      bulkUpdateMs: 37.6315839999952,
    },
    rsxTree: {
      bindMs: 294.7113539999955,
      singleUpdateMs: 0.06787499999336433,
      bulkUpdateMs: 36.34799999999814,
    },
    angular: {
      bindMs: 8.809249999998428,
      singleUpdateMs: 0.01237500000570435,
      bulkUpdateMs: 6.779957999999169,
    },
  },
  {
    bindings: 10000,
    rsxCompiled: {
      bindMs: 595.7966669999951,
      singleUpdateMs: 0.07872950000455603,
      bulkUpdateMs: 69.2245830000029,
    },
    rsxTree: {
      bindMs: 613.0943330000009,
      singleUpdateMs: 0.07910449999690172,
      bulkUpdateMs: 75.67206249999799,
    },
    angular: {
      bindMs: 27.065708000001905,
      singleUpdateMs: 0.015291499999875668,
      bulkUpdateMs: 13.241020999998,
    },
  },
];

export const sameModelExpressionsRow: SameModelRow = {
  bindings: 1000,
  bulkRounds: 10,
  rsxCompiled: {
    bindMs: 15.344124999988708,
    disposeMs: 4.00845800001116,
    singleUpdateMs: 5.9167080000042915,
    bulkUpdateMs: 31.685665999990306,
  },
  rsxTree: {
    bindMs: 590.4162079999951,
    disposeMs: 28.03495899999689,
    singleUpdateMs: 63.286000000007334,
    bulkUpdateMs: 486.1790000000037,
  },
  angular: {
    bindMs: 0.7499169999937294,
    singleUpdateMs: 1.4668329999985872,
    bulkUpdateMs: 13.446458000005805,
  },
};
