/**
 * Benchmark data for the Angular Signals vs rs-x comparison.
 *
 * Generated by:
 *   node --expose-gc rs-x-expression-parser/scripts/benchmark-angular-signals-comparison.mjs
 *
 * Machine: Apple M4, 16 GB RAM, darwin/arm64, Node.js v25.4.0
 * Date: 2026-03-28
 */

export type SignalsComparisonRow = {
  bindings: number;
  rsx: {
    bindMs: number;
    singleUpdateMs: number;
    bulkUpdateMs: number;
  };
  angular: {
    bindMs: number;
    singleUpdateMs: number;
    bulkUpdateMs: number;
  };
};

export type SameModelRow = {
  /** Number of expression bindings (fixed at 1000 — one per generated expression). */
  bindings: number;
  /** Number of sequential x-changes in the bulk-update measurement. */
  bulkRounds: number;
  rsx: {
    /** Create+init only (no dispose). */
    bindMs: number;
    /**
     * Dispose cost measured separately because disposing N expressions from the
     * same model is O(N²): each dispose removes a subscriber from a watcher list
     * that still has N-i entries. This is teardown cost, not setup cost.
     */
    disposeMs: number;
    /** Change x once → all 1000 expressions re-evaluate. */
    singleUpdateMs: number;
    /** bulkRounds sequential x-changes, all 1000 re-evaluate each round. */
    bulkUpdateMs: number;
  };
  angular: {
    bindMs: number;
    singleUpdateMs: number;
    bulkUpdateMs: number;
  };
};

// ─── Scenario 1: Sync identifier ─────────────────────────────────────────────
// Each of the N bindings watches a unique field (`fieldN`) on its own model.
//   rs-x:     rsx('fieldN')(model)         — Proxy-based watching, async microtask
//   Angular:  signal(v) + computed(() => s()) — explicit reactive primitive, sync

export const syncIdentifierRows: SignalsComparisonRow[] = [
  {
    bindings: 1000,
    rsx:     { bindMs: 28.47,  singleUpdateMs: 0.0979, bulkUpdateMs: 6.22  },
    angular: { bindMs: 0.74,   singleUpdateMs: 0.0121, bulkUpdateMs: 0.27  },
  },
  {
    bindings: 3000,
    rsx:     { bindMs: 116.59, singleUpdateMs: 0.0745, bulkUpdateMs: 16.10 },
    angular: { bindMs: 1.45,   singleUpdateMs: 0.0086, bulkUpdateMs: 0.96  },
  },
  {
    bindings: 5000,
    rsx:     { bindMs: 184.08, singleUpdateMs: 0.0742, bulkUpdateMs: 27.51 },
    angular: { bindMs: 3.36,   singleUpdateMs: 0.0111, bulkUpdateMs: 1.58  },
  },
  {
    bindings: 10000,
    rsx:     { bindMs: 352.96, singleUpdateMs: 0.0762, bulkUpdateMs: 53.39 },
    angular: { bindMs: 4.92,   singleUpdateMs: 0.0115, bulkUpdateMs: 3.81  },
  },
];

// ─── Scenario 2: Async identifier (BehaviorSubject) ──────────────────────────
// Each model field is a BehaviorSubject. The binding tracks the emitted value.
//   rs-x:     rsx('stream')(model)              — auto-subscribes to observable
//   Angular:  toSignal(behaviorSubject, {injector}) — synchronous on emit

export const asyncIdentifierRows: SignalsComparisonRow[] = [
  {
    bindings: 1000,
    rsx:     { bindMs: 32.43,  singleUpdateMs: 0.0502, bulkUpdateMs: 7.31  },
    angular: { bindMs: 1.92,   singleUpdateMs: 0.0167, bulkUpdateMs: 0.95  },
  },
  {
    bindings: 3000,
    rsx:     { bindMs: 128.84, singleUpdateMs: 0.0587, bulkUpdateMs: 20.96 },
    angular: { bindMs: 3.51,   singleUpdateMs: 0.0123, bulkUpdateMs: 2.66  },
  },
  {
    bindings: 5000,
    rsx:     { bindMs: 223.56, singleUpdateMs: 0.0583, bulkUpdateMs: 33.29 },
    angular: { bindMs: 5.96,   singleUpdateMs: 0.0112, bulkUpdateMs: 5.39  },
  },
  {
    bindings: 10000,
    rsx:     { bindMs: 458.86, singleUpdateMs: 0.0633, bulkUpdateMs: 63.91 },
    angular: { bindMs: 15.11,  singleUpdateMs: 0.0120, bulkUpdateMs: 11.59 },
  },
];

// ─── Scenario 3: Same-model — all 1000 generated complex expressions ──────────
// All 1000 generated expressions (from generated-benchmark-expression-strings.ts)
// are bound to ONE shared model { x, y }. These are deeply-nested arithmetic
// expressions, each with 60–100+ AST nodes.
//   rs-x:     rsx(generatedExpression[i])({ x, y }) — AST-based evaluation
//   Angular:  computed(() => new Function('x','y', expr)(xSig(), ySig()))
//             — compiled to native JS, full JIT speed
//
// "Single update" = change x once → all 1000 dependents re-evaluate.
// "Bulk update"   = 10 sequential x-changes, 1000 re-evaluations each round.

export const sameModelExpressionsRow: SameModelRow = {
  bindings: 1000,
  bulkRounds: 10,
  // bindMs = create+init only (dispose measured separately).
  // Splitting these apart revealed the real bind cost is ~480ms, not 1800ms.
  // The 1800ms figure seen in earlier runs included ~1450ms of O(N²) dispose.
  rsx:     { bindMs: 483, disposeMs: 1450, singleUpdateMs: 191, bulkUpdateMs: 1883 },
  angular: { bindMs: 0.70, singleUpdateMs: 1.1, bulkUpdateMs: 10.0 },
};
