/**
 * Crossover benchmark data — compiled vs tree engine mode.
 *
 * Generated by:
 *   node --expose-gc --max-old-space-size=8192 \
 *     rs-x-expression-parser/scripts/benchmark-compiled-tree-crossover.mjs
 *   node --expose-gc --max-old-space-size=8192 \
 *     rs-x-expression-parser/scripts/benchmark-compiled-tree-bind-crossover.mjs
 *
 * Expression shape: "x + y + x + y + …" (always exactly 2 unique dependencies)
 *   N pairs of (x + y)  →  4N−1 AST nodes
 *
 * Key insight: compiled bind cost is O(deps=2) regardless of node count,
 * while tree bind cost is O(nodes). For updates, compiled calls a pre-compiled
 * JS function (O(1)); tree re-walks the full AST (O(nodes)).
 *
 * Machine: Apple M4, 16 GB, Node v25.4.0
 * Date: 2026-04-01
 */

export type CrossoverRow = {
  /** Number of AST nodes in the expression. */
  nodeCount: number;
  /** Update engine mode: tree */
  tree: {
    singleUpdateMs: number;
    bulkUpdateMs: number;
  };
  /** Update engine mode: compiled */
  compiled: {
    singleUpdateMs: number;
    bulkUpdateMs: number;
  };
};

export type BindCrossoverRow = {
  /** Number of AST nodes in the expression. */
  nodeCount: number;
  /** Bind engine mode: tree */
  tree: { bindMs: number };
  /** Bind engine mode: compiled */
  compiled: { bindMs: number };
};

/** 1000 unique models, steady-state update time (bindings pre-established). */
export const updateCrossoverRows: CrossoverRow[] = [
  { nodeCount: 3,   tree: { singleUpdateMs: 0.043, bulkUpdateMs: 4.954  }, compiled: { singleUpdateMs: 0.052, bulkUpdateMs: 6.236  } },
  { nodeCount: 7,   tree: { singleUpdateMs: 0.050, bulkUpdateMs: 6.531  }, compiled: { singleUpdateMs: 0.051, bulkUpdateMs: 7.042  } },
  { nodeCount: 15,  tree: { singleUpdateMs: 0.063, bulkUpdateMs: 8.403  }, compiled: { singleUpdateMs: 0.054, bulkUpdateMs: 7.634  } },
  { nodeCount: 27,  tree: { singleUpdateMs: 0.060, bulkUpdateMs: 11.263 }, compiled: { singleUpdateMs: 0.055, bulkUpdateMs: 8.084  } },
  { nodeCount: 47,  tree: { singleUpdateMs: 0.066, bulkUpdateMs: 15.432 }, compiled: { singleUpdateMs: 0.055, bulkUpdateMs: 8.141  } },
  { nodeCount: 79,  tree: { singleUpdateMs: 0.070, bulkUpdateMs: 21.917 }, compiled: { singleUpdateMs: 0.060, bulkUpdateMs: 9.021  } },
  { nodeCount: 131, tree: { singleUpdateMs: 0.091, bulkUpdateMs: 31.103 }, compiled: { singleUpdateMs: 0.056, bulkUpdateMs: 9.166  } },
  { nodeCount: 219, tree: { singleUpdateMs: 0.097, bulkUpdateMs: 46.919 }, compiled: { singleUpdateMs: 0.052, bulkUpdateMs: 9.615  } },
  { nodeCount: 359, tree: { singleUpdateMs: 0.134, bulkUpdateMs: 70.615 }, compiled: { singleUpdateMs: 0.060, bulkUpdateMs: 10.063 } },
];

/** 1000 unique models, cold bind time (create bindings + dispose). */
export const bindCrossoverRows: BindCrossoverRow[] = [
  { nodeCount: 3,   tree: { bindMs: 25.944  }, compiled: { bindMs: 26.147  } },
  { nodeCount: 7,   tree: { bindMs: 44.299  }, compiled: { bindMs: 26.864  } },
  { nodeCount: 15,  tree: { bindMs: 62.708  }, compiled: { bindMs: 30.201  } },
  { nodeCount: 27,  tree: { bindMs: 79.227  }, compiled: { bindMs: 32.565  } },
  { nodeCount: 47,  tree: { bindMs: 123.117 }, compiled: { bindMs: 34.663  } },
  { nodeCount: 79,  tree: { bindMs: 195.612 }, compiled: { bindMs: 32.312  } },
  { nodeCount: 131, tree: { bindMs: 299.048 }, compiled: { bindMs: 32.145  } },
  { nodeCount: 219, tree: { bindMs: 699.465 }, compiled: { bindMs: 78.732  } },
  { nodeCount: 359, tree: { bindMs: 1809.997 }, compiled: { bindMs: 67.223 } },
];

export const crossoverMachine = {
  cpuModel: 'Apple M4',
  nodeVersion: 'v25.4.0',
  bindings: 1000,
  expressionShape: 'x + y + x + y + … (always 2 deps)',
  /** Estimated crossover node count for bind time. */
  bindCrossoverNodes: 3,
  /** Estimated crossover node count for bulk update time. */
  bulkUpdateCrossoverNodes: 10,
  /** Estimated crossover node count for single update time. */
  singleUpdateCrossoverNodes: 8,
};
