/**
 * Crossover benchmark data — compiled vs tree engine mode.
 *
 * Generated by:
 *   node --expose-gc --max-old-space-size=8192 \
 *     rs-x-expression-parser/scripts/benchmark-compiled-tree-crossover.mjs
 *   node --expose-gc --max-old-space-size=8192 \
 *     rs-x-expression-parser/scripts/benchmark-compiled-tree-bind-crossover.mjs
 *
 * Expression shape: "x + y + x + y + …" (always exactly 2 unique dependencies)
 *   N pairs of (x + y)  →  4N−1 AST nodes
 *
 * Key insight: compiled bind cost is O(deps=2) regardless of node count,
 * while tree bind cost is O(nodes). For updates, compiled calls a pre-compiled
 * JS function (O(1)); tree re-walks the full AST (O(nodes)).
 *
 * Machine: Apple M4, 16 GB, Node v25.4.0
 * Date: 2026-04-01
 */

export type CrossoverRow = {
  /** Number of AST nodes in the expression. */
  nodeCount: number;
  /** Update engine mode: tree */
  tree: {
    singleUpdateMs: number;
    bulkUpdateMs: number;
  };
  /** Update engine mode: compiled */
  compiled: {
    singleUpdateMs: number;
    bulkUpdateMs: number;
  };
};

export type BindCrossoverRow = {
  /** Number of AST nodes in the expression. */
  nodeCount: number;
  /** Bind engine mode: tree */
  tree: { bindMs: number };
  /** Bind engine mode: compiled */
  compiled: { bindMs: number };
};

/** 1000 unique models, steady-state update time (bindings pre-established). */
export const updateCrossoverRows: CrossoverRow[] = [
  {
    nodeCount: 3,
    tree: { singleUpdateMs: 0.065, bulkUpdateMs: 6.898 },
    compiled: { singleUpdateMs: 0.068, bulkUpdateMs: 7.388 },
  },
  {
    nodeCount: 7,
    tree: { singleUpdateMs: 0.062, bulkUpdateMs: 8.407 },
    compiled: { singleUpdateMs: 0.073, bulkUpdateMs: 11.112 },
  },
  {
    nodeCount: 15,
    tree: { singleUpdateMs: 0.079, bulkUpdateMs: 15.052 },
    compiled: { singleUpdateMs: 0.096, bulkUpdateMs: 13.432 },
  },
  {
    nodeCount: 27,
    tree: { singleUpdateMs: 0.111, bulkUpdateMs: 24.59 },
    compiled: { singleUpdateMs: 0.108, bulkUpdateMs: 14.463 },
  },
  {
    nodeCount: 47,
    tree: { singleUpdateMs: 0.118, bulkUpdateMs: 30.46 },
    compiled: { singleUpdateMs: 0.104, bulkUpdateMs: 14.888 },
  },
  {
    nodeCount: 79,
    tree: { singleUpdateMs: 0.127, bulkUpdateMs: 44.008 },
    compiled: { singleUpdateMs: 0.11, bulkUpdateMs: 18.127 },
  },
  {
    nodeCount: 131,
    tree: { singleUpdateMs: 0.184, bulkUpdateMs: 71.955 },
    compiled: { singleUpdateMs: 0.111, bulkUpdateMs: 17.38 },
  },
  {
    nodeCount: 219,
    tree: { singleUpdateMs: 0.21, bulkUpdateMs: 155.98 },
    compiled: { singleUpdateMs: 0.121, bulkUpdateMs: 17.765 },
  },
  {
    nodeCount: 359,
    tree: { singleUpdateMs: 1.719, bulkUpdateMs: 621.647 },
    compiled: { singleUpdateMs: 0.135, bulkUpdateMs: 54.728 },
  },
];

/** 1000 unique models, cold bind time (create bindings + dispose). */
export const bindCrossoverRows: BindCrossoverRow[] = [
  { nodeCount: 3, tree: { bindMs: 37.202 }, compiled: { bindMs: 32.812 } },
  { nodeCount: 7, tree: { bindMs: 66.073 }, compiled: { bindMs: 70.154 } },
  { nodeCount: 15, tree: { bindMs: 330.068 }, compiled: { bindMs: 100.051 } },
  { nodeCount: 27, tree: { bindMs: 1231.013 }, compiled: { bindMs: 145.444 } },
  { nodeCount: 47, tree: { bindMs: 596.255 }, compiled: { bindMs: 166.014 } },
  { nodeCount: 79, tree: { bindMs: 1042.953 }, compiled: { bindMs: 129.957 } },
  { nodeCount: 131, tree: { bindMs: 1692.902 }, compiled: { bindMs: 528.165 } },
  { nodeCount: 219, tree: { bindMs: 2626.695 }, compiled: { bindMs: 520.761 } },
  { nodeCount: 359, tree: { bindMs: 4179.42 }, compiled: { bindMs: 338.45 } },
];

export const crossoverMachine = {
  cpuModel: 'Apple M4',
  nodeVersion: 'v25.4.0',
  bindings: 1000,
  expressionShape: 'x + y + x + y + … (always 2 deps)',
  /** Estimated crossover node count for bind time. */
  bindCrossoverNodes: 7,
  /** Estimated crossover node count for bulk update time. */
  bulkUpdateCrossoverNodes: 12,
  /** Estimated crossover node count for single update time. */
  singleUpdateCrossoverNodes: 25,
};
