import { EnumValues } from '@rs-x/core';

export enum CustomTagName {
   Repeater = `rsx-repeater`,
   DataContext = 'rsx-data-context',
   If = 'rsx-if',
   Html = 'rsx-html',
   StaticHtml = 'rsx-static-html',
}
export enum HtmlTagName {
   A = 'a',
   Abbr = 'abbr',
   Address = 'address',
   Area = 'area',
   Article = 'article',
   Aside = 'aside',
   Audio = 'audio',
   B = 'b',
   Base = 'base',
   Bdi = 'bdi',
   Bdo = 'bdo',
   Blockquote = 'blockquote',
   Body = 'body',
   Br = 'br',
   Button = 'button',
   Canvas = 'canvas',
   Caption = 'caption',
   Cite = 'cite',
   Code = 'code',
   Col = 'col',
   Colgroup = 'colgroup',
   Data = 'data',
   Datalist = 'datalist',
   Dd = 'dd',
   Del = 'del',
   Details = 'details',
   Dfn = 'dfn',
   Dialog = 'dialog',
   Dir = 'dir',
   Div = 'div',
   Dl = 'dl',
   Dt = 'dt',
   Em = 'em',
   Embed = 'embed',
   Fieldset = 'fieldset',
   Figcaption = 'figcaption',
   Figure = 'figure',
   Font = 'font',
   Footer = 'footer',
   Form = 'form',
   H1 = 'h1',
   H2 = 'h2',
   H3 = 'h3',
   H4 = 'h4',
   H5 = 'h5',
   H6 = 'h6',
   Head = 'head',
   Header = 'header',
   Hgroup = 'hgroup',
   Hr = 'hr',
   Html = 'html',
   I = 'i',
   Iframe = 'iframe',
   Img = 'img',
   Input = 'input',
   Ins = 'ins',
   Kbd = 'kbd',
   Label = 'label',
   Legend = 'legend',
   Li = 'li',
   Link = 'link',
   Main = 'main',
   Map = 'map',
   Mark = 'mark',
   Menu = 'menu',
   Meta = 'meta',
   Meter = 'meter',
   Nav = 'nav',
   Noscript = 'noscript',
   Object = 'object',
   Ol = 'ol',
   Optgroup = 'optgroup',
   Option = 'option',
   Output = 'output',
   P = 'p',
   Param = 'param',
   Pre = 'pre',
   Progress = 'progress',
   Q = 'q',
   Rp = 'rp',
   Rt = 'rt',
   Ruby = 'ruby',
   S = 's',
   Samp = 'samp',
   Script = 'script',
   Section = 'section',
   Select = 'select',
   Small = 'small',
   Slot = 'slot',
   Source = 'source',
   Span = 'span',
   Strong = 'strong',
   Style = 'style',
   Sub = 'sub',
   Summary = 'summary',
   Sup = 'sup',
   Table = 'table',
   Tbody = 'tbody',
   Td = 'td',
   Template = 'template',
   Textarea = 'textarea',
   Tfoot = 'tfoot',
   Th = 'th',
   Thead = 'thead',
   Time = 'time',
   Title = 'title',
   Tr = 'tr',
   Track = 'track',
   U = 'u',
   Ul = 'ul',
   Var = 'var',
   Video = 'video',
   Wbr = 'wbr',
}

export const htmlTageNames: readonly HtmlTagName[] = EnumValues.getStringValues(
   HtmlTagName
) as HtmlTagName[];

const tagNameRegExp = new RegExp(
   htmlTageNames
      .map((tagName) => `\\b${tagName}\\b`)
      .reduce((a, b) => `${a}|${b}`),
   'i'
);

export function isHtmlTagName(tagName: string): boolean {
   return tagNameRegExp.test(tagName);
}
