export const RsXUIInjectionTokens = {
   IOutputContext: Symbol('IOutputContext'),

   IViewChildContext: Symbol('IViewChildContext'),
   IWebComponentThemeManager: Symbol('IWebComponentThemeManager'),
   IBindingAttributeParser: Symbol('IBindingAttributeParser'),
   WebComponentPathRootResolver: Symbol('WebComponentPathRootResolver'),
   IComponentRegistry: Symbol('IComponentRegistry'),
   IDirectiveRegistry: Symbol('IDirectiveRegistry'),
   IWebComponentElementControllerFactory: Symbol(
      'IWebComponentElementControllerFactory'
   ),
   DomObjectPathObserver: Symbol('DomObjectPathObserver'),
   IRegisteredComponents: Symbol('IRegisteredComponents'),
   IStructuralDirectiveRegistry: Symbol('IStructuralDirectiveRegistry'),
   IBootstrapper: Symbol('IBootstrapper'),
   RepeaterControllerFactory: Symbol('RepeaterControllerFactory'),
   IfControllerFactory: Symbol('IfControllerFactory'),
   HtmlControllerFactory: Symbol('HtmlControllerFactory'),
   StaticHtmlControllerFactory: Symbol('StaticHtmlControllerFactory'),
   IBindingQueue: Symbol('IBindingQueue'),
   ITextContentExpressionParser: Symbol('ITextContentExpressionParser'),
   IBindingsParser: Symbol('IBindingsParser'),
   IBindingValueFactory: Symbol('IBindingValueFactory'),
   IEventObserver: Symbol('IEventObserver'),
   IBindingCollection: Symbol('IBindingCollection'),
   IBindingManagerFactory: Symbol('IBindingManagerFactory'),
   IEventManagerFactory: Symbol('IEventManagerFactory'),
   ISlotCHangeObserverFactory: Symbol('ISlotCHangeObserverFactory'),
   ITemplatedElementFactories: Symbol('ITemplatedElementFactories'),
   RepeaterDirectiveFactory: Symbol('RepeaterDirectiveFactory'),
   IResizeObserverFactory: Symbol('IResizeObserverFactory'),
   IResizeObserverService: Symbol('IResizeObserverService'),
   IHTMLParser: Symbol('IHTMLParser'),
   IDomQuery:  Symbol('IDomQuery'),
   IInputContext:  Symbol('IDomQuery'),
   IElementRemovedObserver: Symbol('IElementRemovedObserver'),
   IDomElementData: Symbol('IDomElementData'),
   IDomService: Symbol('IDomService'),
   IAlignToService: Symbol('IAlignToService'),
   IDomTimer: Symbol('IDomTimer'),
   IDomWindow: Symbol('IDomWindow'),
   IDomElementFactory:  Symbol('IDomElementFactory'),
   IDecoratorValidatorConfiguration: Symbol('IDecoratorValidatorConfiguration'),
   IEventIdentifierResolver: Symbol('IEventIdentifierResolver'),
   DomIdentifierOwnerResolver: Symbol('DomIdentifierOwnerResolver')
};
