import AxeBuilder from '@axe-core/playwright';
import { expect, test } from '@playwright/test';

// All static pages in the site (dynamic [param] routes excluded — covered separately below)
const staticPages = [
  '/',
  '/about',
  '/features',
  '/get-started',
  '/roadmap',
  '/sponsor',
  '/docs',
  '/javascript',
  '/typescript',
  '/react',
  '/vue',
  '/angular',
  '/nextjs',
  '/nodejs',
  '/spa-frameworks',
  '/reactivity',
  '/change-detection',
  '/rxjs',
  '/playground',
  '/docs/core-concepts/first-expression',
  '/docs/core-concepts/cli',
  '/docs/core-concepts/compiler',
  '/docs/core-concepts/compiled-vs-tree',
  '/docs/core-concepts/collections',
  '/docs/core-concepts/async-operations',
  '/docs/core-concepts/batching-transactions',
  '/docs/core-concepts/caching-and-identity',
  '/docs/core-concepts/dates',
  '/docs/core-concepts/dependency-injection',
  '/docs/core-concepts/expression-types',
  '/docs/core-concepts/functions',
  '/docs/core-concepts/identifier-owner-resolver',
  '/docs/core-concepts/member-expressions',
  '/docs/core-concepts/modular-expressions',
  '/docs/core-concepts/performance',
  '/docs/core-concepts/performance-demo',
  '/docs/core-concepts/performance-identifiers',
  '/docs/core-concepts/performance-memory',
  '/docs/core-concepts/performance-parse',
  '/docs/core-concepts/performance-report',
  '/docs/core-concepts/performance-v1-v2',
  '/docs/core-concepts/readonly-properties',
  '/docs/core-concepts/rsx-config',
  '/docs/core-concepts/side-effects',
  '/docs/core-concepts/angular-signals-comparison',
  '/docs/frameworks/angular',
  '/docs/frameworks/react',
  '/docs/frameworks/rxjs',
  '/docs/frameworks/vue',
  '/docs/async-operations',
  '/docs/collections',
  '/docs/custom-data-types',
  '/docs/modular-expressions',
  '/docs/observation',
  '/docs/abstract-expression',
  '/docs/array-index-owner-resolver',
  '/docs/change-hook',
  '/docs/core-api',
  '/docs/default-identifier-owner-resolver',
  '/docs/expression-change-commit-handler',
  '/docs/expression-change-tracker-manager',
  '/docs/expression-change-transaction-manager',
  '/docs/expression-creation',
  '/docs/expression-type',
  '/docs/global-identifier-owner-resolver',
  '/docs/iexpression',
  '/docs/iidentifier-owner-resolver',
  '/docs/index-watch-rule',
  '/docs/iproxy-registry',
  '/docs/irsx-options',
  '/docs/keyed-instance-factory',
  '/docs/map-key-owner-resolver',
  '/docs/property-owner-resolver',
  '/docs/rsx-function',
  '/docs/set-key-owner-resolver',
  '/docs/state-manager-api',
  '/docs/core-api/module/deep-clone',
  '/docs/core-api/module/dependency-injection-ts',
  '/docs/core-api/module/equality-service',
  '/docs/core-api/module/error-log',
  '/docs/core-api/module/exceptions',
  '/docs/core-api/module/function-call-index',
  '/docs/core-api/module/function-call-result-cache',
  '/docs/core-api/module/guid',
  '/docs/core-api/module/index-value-accessor',
  '/docs/core-api/module/keyed-instance-factory',
  '/docs/core-api/module/object-store',
  '/docs/core-api/module/proxy-registry',
  '/docs/core-api/module/rs-x-core-injection-tokens-ts',
  '/docs/core-api/module/rs-x-core-module-ts',
  '/docs/core-api/module/sequence-id',
  '/docs/core-api/module/types',
  '/docs/core-api/module/value-metadata',
  '/docs/core-api/module/wait-for-event',
];

for (const path of staticPages) {
  test(`${path} — no axe violations`, async ({ page }) => {
    await page.goto(path);

    const results = await new AxeBuilder({ page })
      .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
      .analyze();

    expect(results.violations).toEqual([]);
  });
}
