export const RsXExpressionParserInjectionTokens = {
  PropertyOwnerResolver: Symbol('PropertyOwnerResolver'),
  ArrayIndexOwnerResolver: Symbol('ArrayIndexOwnerResolver'),
  MapKeyOwnerResolver: Symbol('MapKeyOwnerResolver'),
  SetKeyOwnerResolver: Symbol('SetKeyOwnerResolver'),
  GlobalIdentifierOwnerResolver: Symbol('GlobalIdentifierOwnerResolver'),
  IdentifierOwnerResolver: Symbol('IdentifierOwnerResolver'),
  IIdentifierOwnerResolverList: Symbol('IIdentifierOwnerResolverList'),
  IExpressionManager: Symbol('IExpressionManager'),
  IExpressionChangeTransactionManager: Symbol(
    'IExpressionChangeTransactionManager',
  ),
  IExpressionTreeBuilder: Symbol('IExpressionTreeBuilder'),
  IExpressionParser: Symbol('IExpressionParser'),
  IJsExpressionAstParser: Symbol('IJsExpressionAstParser'),
  IExpressionFactory: Symbol('IExpressionFactory'),
  IExpressionObserverProxyPairFactory: Symbol(
    'IExpressionObserverProxyPairFactory',
  ),
  IExpressionIndexAccessor: Symbol('IExpressionIndexAccessor'),
  IExpressionObserverFactory: Symbol('IExpressionObserverFactory'),
  IExpressionCache: Symbol('IExpressionCache'),
  ICompiledExpressionCompiler: Symbol('ICompiledExpressionCompiler'),
  ITreeExpressionEngine: Symbol('ITreeExpressionEngine'),
  ICompiledExpressionEngine: Symbol('ICompiledExpressionEngine'),
  IExpressionEngineSelector: Symbol('IExpressionEngineSelector'),
  IExpressionServices: Symbol('IExpressionServices'),
  IExpressionEvaluateManager: Symbol('IExpressionEvaluateManager'),
  ExpressiomMetadata: Symbol('ExpressiomMetadata'),
  IExpressionChangePlayback: Symbol('IExpressionChangePlayback'),
  IExpressionChangeTrackerManager: Symbol('IExpressionChangeTrackerManager'),
  IExpressionIdProvider: Symbol('IExpressionIdProvider'),
  IIdentifierWatchRuleFactory: Symbol('IIdentifierWatchRuleFactory'),
};
