export const RsXExpressionParserInjectionTokens = {
   PropertyOwnerResolver: Symbol('PropertyOwnerResolver'),
   ArrayIndexOwnerResolver: Symbol('ArrayIndexOwnerResolver'),
   MapKeyOwnerResolver: Symbol('MapKeyOwnerResolver'),
   IdentifierOwnerResolver: Symbol('IdentifierOwnerResolver'),
   IIdentifierOwnerResolverList:  Symbol('IIdentifierOwnerResolverList'),
   IExpressionManager: Symbol('IExpressionManager'),
   IExpressionChangeTransactionManager: Symbol('IExpressionChangeTransactionManager'),
   IExpressionParser: Symbol('IExpressionParser'),
   IExpressionFactory:  Symbol('IExpressionFactory'),
   IExpressionObserverProxyPairFactory: Symbol('IExpressionObserverProxyPairFactory'),
   IExpressionIndexAccessor: Symbol('IExpressionIndexAccessor'),
   IExpressionObserverFactory: Symbol('IExpressionObserverFactory'),
   IExpressionCache: Symbol('IExpressionCache'),
};
