export const RsXCoreInjectionTokens = {
   IInjectionContainer: Symbol('IInjectionContainer'),
   IErrorLog: Symbol('IErrorLog'),
   IIndexValueAccessor: Symbol('IIndexValueAccessor'),
   IMapKeyAccessor: Symbol('IMapKeyAccessor'),
   ISetKeyAccessor: Symbol('ISetKeyAccessor'),
   IArrayIndexAccessor: Symbol('IArrayIndexAccessor'),
   IPropertyValueAccessor: Symbol('IPropertyValueAccessor'),
   IMethodAccessor: Symbol('IPropertyValueAccessor'),
   IDatePropertyAccessor: Symbol('IDatePropertyAccessor'),
   IDeepClone: Symbol('IDeepClone'),
   IEqualityService: Symbol('IEqualityService'),
   IObservableAccessor: Symbol('IObservableAccessor'),
   IPromiseAccessor: Symbol('IPromiseAccessor'),
   IIndexValueAccessorList:  Symbol('IIndexValueAccessorList'),
   ISequenceIdFactory:  Symbol('ISequenceIdFactory'),
   IFunctionCallIndexFactory: Symbol('IFunctionCallIndexFactory'),
   IFunctionCallResultCacheFactory: Symbol('IFunctionCallResultCacheFactory'),
   IGuidFactory: Symbol('IGuidFactory')
};
